[target.mips-unknown-linux-musl]
linker = "gcc-crt-wrapper"
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s", "-Zunstable-options", "-Cpanic=immediate-abort"]

[target.mipsel-unknown-linux-musl]
linker = "gcc-crt-wrapper"
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s", "-Zunstable-options", "-Cpanic=immediate-abort"]

[target.mips64-unknown-linux-muslabi64]
linker = "gcc-crt-wrapper"
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s", "-Zunstable-options", "-Cpanic=immediate-abort"]

[target.mips64el-unknown-linux-muslabi64]
linker = "gcc-crt-wrapper"
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s", "-Zunstable-options", "-Cpanic=immediate-abort"]

[target.aarch64-unknown-linux-musl]
linker = "/home/agent_007/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
rustflags = ["-C", "target-cpu=cortex-a53", "-Clink-arg=-s"]
